[package]
name = "ledger-formatter"
version = "0.1.0"
authors = ["Ivan Fraixedes <ivan@fraixed.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
